#!/bin/bash

# Script to generate a C# dictionary file from all SVG icons
# This improves build performance by embedding icons as a single compiled dictionary
# instead of processing hundreds of individual embedded resources

set -e

ICONS_DIR="icons"
OUTPUT_FILE="LucideIconsDictionary.cs"
TEMP_FILE="${OUTPUT_FILE}.tmp"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Generating C# dictionary from SVG icons...${NC}"

# Check if icons directory exists
if [ ! -d "$ICONS_DIR" ]; then
    echo "Error: Icons directory '$ICONS_DIR' not found"
    exit 1
fi

# Count SVG files
SVG_COUNT=$(find "$ICONS_DIR" -name "*.svg" | wc -l)

if [ "$SVG_COUNT" -eq 0 ]; then
    echo "Warning: No SVG files found in '$ICONS_DIR' directory"
    exit 1
fi

# Start writing the C# file
cat > "$TEMP_FILE" << 'EOF'
using System.Collections.Generic;

namespace EstusLabs.Lucide;

/// <summary>
/// Auto-generated dictionary of Lucide icon SVGs.
/// This file is generated by generate-icons-dictionary.sh - do not edit manually.
/// </summary>
public static class LucideIconsDictionary
{
    public static readonly Dictionary<string, string> Icons = new()
    {
EOF

# Process each SVG file
FIRST=true
find "$ICONS_DIR" -name "*.svg" -type f | sort | while read -r svg_file; do
    # Get the icon name (filename without extension, lowercase)
    icon_name=$(basename "$svg_file" .svg | tr '[:upper:]' '[:lower:]')
    
    # Read SVG content and escape it for C# string literal
    # Replace " with \" and escape newlines
    svg_content=$(cat "$svg_file" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
    
    if [ "$FIRST" = true ]; then
        FIRST=false
    else
        echo "," >> "$TEMP_FILE"
    fi
    
    # Write dictionary entry
    echo -n "        { \"$icon_name\", \"$svg_content\" }" >> "$TEMP_FILE"
done

# Close the dictionary and class
cat >> "$TEMP_FILE" << 'EOF'

    };
}
EOF

# Replace the old file with the new one
mv "$TEMP_FILE" "$OUTPUT_FILE"

echo -e "${GREEN}Successfully generated dictionary with $SVG_COUNT icons in '$OUTPUT_FILE'${NC}"